import { Inter } from 'next/font/google'
import './globals.css'
import { AppContextProvider } from './app-context';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <AppContextProvider>
    <html lang="fr">
      <body className={inter.className}>
        <main className="flex flex-col justify-between p-8">
          {children}
        </main>
      </body>
    </html>
    </AppContextProvider>
  );
}
